apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-secrets
  namespace: jenkins
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-secrets
  dataFrom:
    - extract:
        key: shopglobe/prod/jenkins
